### ISSUE TITLE
Unable to load obs.dll error

### ISSUE THREAD

**Issue by Raj123456788** [GoaLitiuM/libobs-sharp#17]
Hi There,
 when i run the Testform.cs it gives me this error? 
Unable to load DLL 'obs.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) Can you please let me know what am I missing?

**Comment by GoaLitiuM** [comment]
You need to build obs-studio and have all the built files (from "rundir/32bit/" or "rundir/64bit/") in the project's output directory ("test/bin/Debug").

...Or just change the project's output directory to the obs-studio's output directory for now till there's a better solution for this.

**Comment by Raj123456788** [comment]
I am sorry have never worked on C++ before but how do you build the
obs-studio. Can you please give me detail steps how to get required dll? Is
there a palace I can download and place those dll in output directory of
libobs?

**Comment by Raj123456788** [comment]
Hello There,
I am still waiting for reply. Can you please respond ASAP?

**Comment by GoaLitiuM** [comment]
Run CMake again for obs-studio and enable BUILD_TESTS variable before generating the project files again.

**Comment by Raj123456788** [comment]
I tried that but getting  Cannot find libdshowcapture/source/capture-filter.cpp Error in Cmake. Is there another way to get the dll's? Waiting for your reply.

**Comment by Raj123456788** [comment]
Use GSEffect solid = Obs.GetBaseEffect(ObsBaseEffect.Solid) for Unable to find an entry point named 'obs_get_solid_effect' in DLL 'obs.dll'.
