### ISSUE TITLE
Issues with building obs-studio

### ISSUE THREAD

**Issue by Raj123456788** [GoaLitiuM/libobs-sharp#18]
I followed this https://github.com/jp9000/obs-studio to build Obs Studio to get 31 projects but ended up with these 49errors:freetype.lib(bdf.obj) : error LNK2019: unresolved external symbol sprintf referenced in function _bdf_parse_properties

the project text-Freetype2 is throwing errors: error LNK2019: unresolved external symbol sprintf referenced in function _bdf_parse_properties

Can you please tell me troubleshooting steps?

**Comment by GoaLitiuM** [comment]
There is some issues in building obs-studio with VS2015, try building the project with VS2013 compiler.

If you have any more issues with building obs-studio, please follow their instructions in their GitHub wiki pages.
